create table if not exists public.website_demo_requests (
  id bigint generated by default as identity primary key,
  full_name text not null,
  work_email text not null,
  company text not null,
  job_title text not null,
  team_size text not null,
  hiring_volume text not null,
  preferred_region text not null,
  message text not null default '',
  source text not null default 'valases_website',
  status text not null default 'new',
  created_at timestamptz not null default now(),
  constraint website_demo_requests_status_check check (status in ('new', 'contacted', 'qualified', 'closed')),
  constraint website_demo_requests_region_check check (preferred_region in ('mumbai', 'tokyo', 'discuss'))
);

alter table public.website_demo_requests enable row level security;

revoke all on table public.website_demo_requests from anon, authenticated;
grant all on table public.website_demo_requests to service_role;

create index if not exists website_demo_requests_created_at_idx
  on public.website_demo_requests (created_at desc);

create index if not exists website_demo_requests_status_idx
  on public.website_demo_requests (status);
